server:
  port: 9000
spring:
  application:
    name: api-gateway # 应用名
  cloud:
    gateway:
      # 路由si(集合)
      routes:
        # id唯一标识，(可自定义)
        - id: 1
          # 路由服务地址
          uri: https://gitee.com/
          # 路由拦截地址(断言)
          predicates:
            - Path=/GN
        - id: 2
          uri: https://github.com/sunweisheng
          predicates:
            - Path=/GW
        - id: host_route
          uri: http://httpbin.org:80/get
          predicates:
            - Host=**.csdn.** # 请求域名携带csdn的,则转发
        - id: query_route
          uri: http://163.com
          predicates:
            - Query=username, zzz* # 请求参数含有username,且值满足zzz开头的,则转发(对值的匹配可以省略)
        - id: header_route
          uri: http://httpbin.org:80/get
          predicates:
            - Header=request, \d+ # 如果请求头含有request,且为数字,则转发

